services:

  banco:
    image: postgres:15
    container_name: analisarpro_banco
    restart: always
    environment:
      POSTGRES_USER: analisarpro
      POSTGRES_PASSWORD: analisar123
      POSTGRES_DB: analisarpro
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: analisar_backend
    restart: always
    depends_on:
      banco:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://analisarpro:analisar123@banco:5432/analisarpro
    ports:
      - "8000:8000"

  administrador:
    image: adminer:latest
    container_name: analisarpro_adminer
    restart: always
    depends_on:
      banco:
        condition: service_started
    ports:
      - "8085:8080"

  frontend:
    build:
      context: ./front-end
    container_name: analisarpro_frontend
    restart: always
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:80"
